"""empty message

Revision ID: 6b3395b1a11e
Revises: 28ac21f21ea7
Create Date: 2026-07-20 21:07:14.130143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3395b1a11e'
down_revision = '28ac21f21ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agua', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_agua_usuario_id', 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agua', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agua_usuario_id', type_='foreignkey')

    # ### end Alembic commands ###
