"""empty message

Revision ID: 92a9120eca1c
Revises: 28ac21f21ea7
Create Date: 2026-07-20 21:20:07.250586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a9120eca1c'
down_revision = '28ac21f21ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agua', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_agua_usuario_id', 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agua', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agua_usuario_id', type_='foreignkey')
        batch_op.alter_column('hora',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
